[tool.poetry]
name = "physics_tutor"
version = "0.1.0"
description = "An LLM-based personalized physics tutor."
authors = ["Aaditya"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "*"
uvicorn = "*"
openai = "*"
python-dotenv = "*"
streamlit = "*"
requests = "*"