[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[client]
# The main entrypoint for the application
mainScriptPath = "streamlit_app.py"
