# Streamlit Cloud Secrets Configuration
# This file serves as a template. In Streamlit Cloud, add these secrets in the dashboard.

[api_keys]
openai = "" # Your OpenAI API key
anthropic = "" # Optional: Your Anthropic API key
